services:
  frontend:
    container_name: barber-frontend-app-${NODE_ENV}
    image: ghcr.io/viniciusgnandt/frontend-app:latest
    expose:
      - "80"
    environment:
      NODE_ENV: ${NODE_ENV}
      BACKEND_URL: ${BACKEND_URL}
      
    restart: unless-stopped
    networks:
      - agenda-net

networks:
  agenda-net:
    external: true