services:
  api:
    container_name: barber-backend-test_${NODE_ENV}
    image: ghcr.io/viniciusgnandt/backend:latest
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - agenda-net

networks:
  agenda-net:
    external: true