services:
  api:
    container_name: barber-backend-test_${NODE_ENV}
    image: ghcr.io/viniciusgnandt/backend:latest
    expose:
      - "3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - OCI_REGION=${OCI_REGION}
      - OCI_NAMESPACE=${OCI_NAMESPACE}
      - OCI_BUCKET_NAME=${OCI_BUCKET_NAME}
      - OCI_ACCESS_KEY_ID=${OCI_ACCESS_KEY_ID}
      - OCI_SECRET_ACCESS_KEY=${OCI_SECRET_ACCESS_KEY}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - ALLOWED_FILE_TYPES=${ALLOWED_FILE_TYPES}
    restart: unless-stopped
    networks:
      - agenda-net

networks:
  agenda-net:
    external: true