# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  api:
    container_name: barber-backend-${NODE_ENV}
    image: ghcr.io/viniciusgnandt/backend:latest
    expose:
      - "3000"
    env_file:
      - .env

    restart: unless-stopped
    networks:
      - agenda-net

networks:
  agenda-net:
    external: true
